
version: '3'

services:
  app:
    build: .
    ports:
      - "4040:4040"
    environment:
      - PORT=4040
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ticketops
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ticketops
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
